### ISSUE TITLE
Add the option to change the margin line?

### ISSUE THREAD

**Issue by reece-bennett** [Hirse/brackets-print-margin#5]
I'm using a dark theme and having a bright white line in the editor is very off putting. Would it be possible to add a config to change the colour?

**Comment by Hirse** [comment]
Definitely. What color would you like for the dark theme?

**Comment by Hirse** [comment]
Check out 52eb81e127c0922c69779f38acc2a04d4a518e78 please.
I have added a darker line that will be automatically selected if Brackets has a dark theme.
