### ISSUE TITLE
Print margin not visible in v0.3.1

### ISSUE THREAD

**Issue by asinitson** [Hirse/brackets-print-margin#7]
Brackets notified me about update. After updating to v0.3.1 Print Margin is no longer visible.

**Comment by Hirse** [comment]
For that release, I used a grunt-script to create the archive but forgot one folder.
Should be fixed in 0.3.2 (8019354ba2b1ae2bdc43e48b33470001094db2ab).

**Comment by asinitson** [comment]
Confirming that it works in v0.3.2. Thank you for the quick response. Nice job!
