### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by waffledonkey** [Hirse/brackets-print-margin#8]
This is a low priority, but you recently made an update so I thought I'd mention it.

There is a deprecation warning in the console advising to not use global `Mustache` (`main.js; line 56`) and instead to use `brackets.getModule("thirdparty/mustache/mustache")`. 

Cheers.

**Comment by Hirse** [comment]
Thanks for opening this issue.

However, the latest update was to explicitly address that problem.
Can you please update, reload Brackets and check again?

If you are still seeing this, please also provide the version of your Brackets and extension.

**Comment by waffledonkey** [comment]
My sincere apologies.  You are right.  I had upgraded to 1.8, but extension downloading isn't happy from behind a proxy, so I downgraded back to 1.7.
